apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  INTERNAL_API_BASE_URL: "__INTERNAL_API_BASE_URL__"
  GITEA_BASE_URL: "__GITEA_BASE_URL__"
  ENV: "__ENV__"
  SPACE_STORAGE_ROOT: "__SPACE_STORAGE_ROOT__"
  SPACE_STORAGE_SUBPATH: "__SPACE_STORAGE_SUBPATH__"
  PLATFORM_SPACE_ID: "__PLATFORM_SPACE_ID__"
  CONFIGS_SUBPATH: "__CONFIGS_SUBPATH__"
