appName: cohub-agent
namespace: cohub
serviceName: cohub-agent
port: 8788
image: git.talesofai.com/talesofai/cohub-agent:v20260325
env: prod
workerSecret: ""
sessionsDir: /sessions
SPACE_STORAGE_SUBPATH: "cohub-prod"
