appName: cohub-agent
namespace: cohub
serviceName: cohub-agent
port: 8788
image: git.talesofai.com/talesofai/cohub-agent:v0.6.8
env: prod
workerSecret: ""
workspaceRoot: /space-storage
sessionsDir: /sessions
platformConfigRoot: /configs
spaceStoragePvc: cohub-spaces-pvc
workspaceSubpath: workspaces/prod
sessionsSubpath: sessions/prod
configsSubpath: configs/prod
sessionsNamespace: cohub-sessions
