appName: cohub-agent
namespace: cohub
serviceName: cohub-agent
port: 8788
image: git.talesofai.com/talesofai/cohub-agent:v1.43.0
replicas: "4"
maxUnavailable: "0"
maxSurge: "1"
terminationGracePeriodSeconds: "2400"
imagePullPolicy: IfNotPresent
env: prod
logLevel: info
workerSecret: ""
workspaceRoot: /space-storage
sessionsDir: /sessions
platformConfigRoot: /configs
spaceStoragePvc: cohub-spaces-pvc
workspaceSubpath: workspaces/prod
sessionsSubpath: sessions/prod
configsSubpath: configs/prod
sessionsNamespace: cohub-sessions
agentWorkerConcurrency: "8"
agentShutdownDrainTimeoutMs: "2100000"
resourceRequestCpu: "0.5"
resourceRequestMemory: "512Mi"
resourceLimitCpu: "2"
resourceLimitMemory: "2Gi"
