# 请填写后再部署
apiVersion: v1
kind: Secret
metadata:
  name: cohub-worker-dev-secrets
  namespace: cohub-dev
type: Opaque
stringData:
  DATABASE_URL: "__DATABASE_URL__"
  REDIS_URL: "__REDIS_URL__"
  WORKER_SECRET: "__WORKER_SECRET__"
