appName: cohub-agent-dev
namespace: cohub-dev
serviceName: cohub-agent-dev
port: 8788
image: git.talesofai.com/talesofai/cohub-agent:main-17f713a
replicas: "1"
maxUnavailable: "0"
maxSurge: "1"
terminationGracePeriodSeconds: "2400"
imagePullPolicy: Always
env: dev
logLevel: debug
workerSecret: ""
workspaceRoot: /space-storage
sessionsDir: /sessions
platformConfigRoot: /configs
spaceStoragePvc: cohub-spaces-pvc
workspaceSubpath: workspaces/dev
sessionsSubpath: sessions/dev
configsSubpath: configs/dev
sessionsNamespace: cohub-sessions-dev
agentWorkerConcurrency: "8"
agentShutdownDrainTimeoutMs: "2100000"
resourceRequestCpu: "0.1"
resourceRequestMemory: "256Mi"
resourceLimitCpu: "1"
resourceLimitMemory: "1024Mi"
