appName: cohub-agent-dev
namespace: cohub-dev
serviceName: cohub-agent-dev
port: 8788
image: git.talesofai.com/talesofai/cohub-agent:latest
env: dev
logLevel: debug
workerSecret: ""
workspaceRoot: /space-storage
sessionsDir: /sessions
platformConfigRoot: /configs
spaceStoragePvc: cohub-spaces-pvc
workspaceSubpath: workspaces/dev
sessionsSubpath: sessions/dev
configsSubpath: configs/dev
sessionsNamespace: cohub-sessions-dev
agentWorkerConcurrency: "8"
