apiVersion: v1
kind: ConfigMap
metadata:
  name: __APP_NAME__-config
  namespace: __NAMESPACE__
data:
  PORT: "__PORT__"
  AUTH_BASE_URL: "__AUTH_BASE_URL__"
  GITEA_BASE_URL: "__GITEA_BASE_URL__"
  WEB_ORIGIN: "__WEB_ORIGIN__"
  TOKEN_COOKIE_NAME: "__TOKEN_COOKIE_NAME__"
