# 请填写后再部署
NAMESPACE: "cohub"
APP_NAME: "cohub-worker"
USER_APP_NAME: "cohub-user-worker"
SYSTEM_APP_NAME: "cohub-system-worker"

IMAGE_REPOSITORY: "git.talesofai.com/talesofai/cohub-worker"
IMAGE_TAG: "v1.43.0"
IMAGE_PULL_POLICY: "IfNotPresent"
IMAGE_PULL_SECRET: "gitea-registry"

USER_REPLICAS: "20"
USER_REQUEST_CPU: "100m"
USER_REQUEST_MEMORY: "128Mi"
USER_LIMIT_CPU: "1"
USER_LIMIT_MEMORY: "512Mi"

SYSTEM_REPLICAS: "10"
SYSTEM_REQUEST_CPU: "100m"
SYSTEM_REQUEST_MEMORY: "128Mi"
SYSTEM_LIMIT_CPU: "1"
SYSTEM_LIMIT_MEMORY: "512Mi"
FS_CDN_WORKER_CONCURRENCY: "4"

INTERNAL_API_BASE_URL: "http://cohub-api:8787"
GITEA_BASE_URL: "https://gitea.cohub.run"
GITEA_ORG: "cohub-checkpoints-prod"
SPACE_STORAGE_ROOT: "/space-storage"
SPACE_SYSTEM_ROOT: "/system-storage"
CHECKPOINT_CACHE_ROOT: "/checkpoint-cache"
SPACE_STORAGE_PVC: "cohub-spaces-pvc"
SPACE_SYSTEM_PVC: "cohub-system-pvc"
CHECKPOINT_CACHE_PVC: "cohub-checkpoints-pvc"
SPACE_STORAGE_SUBPATH: "workspaces/prod"
PLATFORM_CONFIG_ROOT: "/configs"
PLATFORM_SPACE_ID: "1de0f2fc-1ab6-4072-9d77-9781a1870b85"
CONFIGS_SUBPATH: "configs/prod"
ENV: "prod"
LOG_LEVEL: "info"

# ========== OSS 配置 ==========
TURN_OBJECT_S3_ENDPOINT: "https://oss-us-west-1-internal.aliyuncs.com"
TURN_OBJECT_S3_REGION: "us-west-1"
TURN_OBJECT_S3_BUCKET: "cohub-sessions"
CHECKPOINT_ASSET_OSS_ENDPOINT: "https://oss-us-west-1-internal.aliyuncs.com"
CHECKPOINT_ASSET_OSS_REGION: "us-west-1"
CHECKPOINT_ASSET_OSS_BUCKET: "cohub-checkpoint-assets"
MAX_UNAVAILABLE: "0"
MAX_SURGE: "1"
TERMINATION_GRACE_PERIOD_SECONDS: "360"
TASK_WORKER_SHUTDOWN_TIMEOUT_MS: "300000"
FS_CDN_WORKER_SHUTDOWN_TIMEOUT_MS: "300000"
