import type { Context } from "@opentelemetry/api";
import type { ReadableSpan, Span, SpanExporter, SpanProcessor } from "@opentelemetry/sdk-trace-base";

const REDIS_SCOPE_NAME = "@opentelemetry/instrumentation-ioredis";
const REALTIME_AGENT_PATCH_CHANNEL = "pubsub:realtime:agent_patches";
const REALTIME_OUTBOUND_CHANNEL = "pubsub:realtime:outbound";
const STREAM_SNAPSHOT_PREFIX = "session:stream:snapshot:";

export type NoiseFilteringOptions = {
  /** Drop low-signal Redis spans generated by streaming realtime fan-out. */
  dropRealtimeRedisSpans?: boolean;
};

export function shouldDropNoisySpan(span: ReadableSpan, options: NoiseFilteringOptions = {}) {
  if (options.dropRealtimeRedisSpans === false) return false;
  if (span.instrumentationScope.name !== REDIS_SCOPE_NAME) return false;

  const statement = String(span.attributes["db.statement"] ?? span.attributes["db.query.text"] ?? "").toLowerCase();
  if (!statement) return false;

  return (
    statement.includes(REALTIME_AGENT_PATCH_CHANNEL) ||
    statement.includes(REALTIME_OUTBOUND_CHANNEL) ||
    statement.includes(STREAM_SNAPSHOT_PREFIX)
  );
}

export class FilteringSpanExporter implements SpanExporter {
  constructor(
    private readonly delegate: SpanExporter,
    private readonly options: NoiseFilteringOptions = {},
  ) {}

  export(spans: ReadableSpan[], resultCallback: Parameters<SpanExporter["export"]>[1]) {
    const filtered = spans.filter((span) => !shouldDropNoisySpan(span, this.options));
    if (filtered.length === 0) {
      resultCallback({ code: 0 });
      return;
    }
    this.delegate.export(filtered, resultCallback);
  }

  shutdown() {
    return this.delegate.shutdown();
  }

  forceFlush() {
    return this.delegate.forceFlush?.() ?? Promise.resolve();
  }
}

export class FilteringSpanProcessor implements SpanProcessor {
  constructor(
    private readonly delegate: SpanProcessor,
    private readonly options: NoiseFilteringOptions = {},
  ) {}

  onStart(span: Span, parentContext: Context) {
    this.delegate.onStart(span, parentContext);
  }

  onEnding(span: Span) {
    this.delegate.onEnding?.(span);
  }

  onEnd(span: ReadableSpan) {
    if (shouldDropNoisySpan(span, this.options)) return;
    this.delegate.onEnd(span);
  }

  forceFlush() {
    return this.delegate.forceFlush();
  }

  shutdown() {
    return this.delegate.shutdown();
  }
}
